use infsci2710;
INSERT INTO region (regionID,name,regionManagerID) VALUES (1,'A',1001);
INSERT INTO region (regionID,name,regionManagerID) VALUES (2,'B',1002);
INSERT INTO region (regionID,name,regionManagerID) VALUES (3,'C',1003);
INSERT INTO region (regionID,name,regionManagerID) VALUES (4,'D',1004);
INSERT INTO region (regionID,name,regionManagerID) VALUES (5,'E',1005);
INSERT INTO region (regionID,name,regionManagerID) VALUES (6,'F',1006);
INSERT INTO region (regionID,name,regionManagerID) VALUES (7,'G',1007);
INSERT INTO region (regionID,name,regionManagerID) VALUES (8,'H',1008);
INSERT INTO region (regionID,name,regionManagerID) VALUES (9,'I',1009);
INSERT INTO region (regionID,name,regionManagerID) VALUES (10,'J',1010);
