use infsci2710;
INSERT INTO login (employeeID,password,userType) VALUES (1,'1','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (2,'2','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (3,'3','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (4,'4','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (5,'5','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (6,'6','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (7,'7','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (8,'8','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (9,'9','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (10,'10','salesman');
INSERT INTO login (employeeID,password,userType) VALUES (101,'101','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (102,'102','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (103,'103','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (1001,'1001','store manager');
INSERT INTO login (employeeID,password,userType) VALUES (1002,'1002','region manager');
